version: '3'
services:

  authentification-service:
    container_name: 'authentification-service'
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - APPLICATION=authentification-service
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      PORT: 3000
    networks:
      - app-network
    ports:
      - "3000:3000"

  nats:
    image: nats
    ports:
      - '8222:8222'
    networks:
      - app-network
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fetlison
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: